package de.sivag.planningpoker.migration;

import org.flywaydb.core.Flyway;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Prüft die Flyway-Migrationen gegen eine leere Datenbank und gegen ein
 * Schema, wie es Hibernate für Version 1.0.1 per ddl-auto=update angelegt hat.
 *
 * @author Nico Hoffmann
 * @version 1.0
 */
class FlywayMigrationTest {

    // ====================================
    // Tests
    // ====================================

    @Test
    @DisplayName("Leere Datenbank: alle Migrationen laufen, Schema ist vollständig")
    void emptyDatabase_getsFullSchema() throws SQLException {
        JdbcDataSource ds = newDatabase();

        migrate(ds);

        assertThat(columnExists(ds, "PARTICIPANTS", "TOKEN")).isTrue();
        assertThat(columnExists(ds, "SESSIONS", "LAST_ACTIVITY_AT")).isTrue();
        assertThat(columnExists(ds, "VOTES", "CARD_VALUE")).isTrue();
    }

    @Test
    @DisplayName("Datenbank aus 1.0.1: Token-Spalte und letzte Aktivität werden ergänzt, Daten bleiben")
    void legacyDatabase_isUpgradedInPlace() throws SQLException {
        JdbcDataSource ds = newDatabase();
        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            // Schema 1.0.1, wie von Hibernate erzeugt (ohne token, ohne last_activity_at)
            st.execute("""
                    create table sessions (
                        auto_reveal boolean not null, moderator_can_vote boolean not null,
                        show_only_total boolean default true not null, show_topic boolean not null,
                        created_at timestamp(6) not null, current_ticket_id bigint,
                        id bigint generated by default as identity, room_code varchar(8) not null unique,
                        estimation_method varchar(255) not null, status varchar(255) not null,
                        primary key (id))""");
            st.execute("""
                    create table participants (
                        moderator boolean not null, id bigint generated by default as identity,
                        joined_at timestamp(6) not null, session_id bigint not null,
                        browser_id varchar(36), name varchar(100) not null, role varchar(255) not null,
                        primary key (id), foreign key (session_id) references sessions)""");
            st.execute("""
                    create table tickets (
                        order_index integer not null, id bigint generated by default as identity,
                        session_id bigint not null, final_estimate varchar(20),
                        status varchar(255) not null, title varchar(255) not null,
                        primary key (id), foreign key (session_id) references sessions)""");
            st.execute("""
                    create table votes (
                        id bigint generated by default as identity, participant_id bigint not null,
                        session_id bigint not null, voted_at timestamp(6) not null,
                        card_value varchar(10) not null, primary key (id),
                        constraint uq_vote_session_participant unique (session_id, participant_id))""");
            st.execute("""
                    insert into sessions (auto_reveal, moderator_can_vote, show_topic, created_at,
                                          room_code, estimation_method, status)
                    values (false, true, false, timestamp '2026-09-01 10:00:00', 'ABCD1234', 'FIBONACCI', 'WAITING')""");
        }

        migrate(ds);

        assertThat(columnExists(ds, "PARTICIPANTS", "TOKEN")).isTrue();
        try (Connection c = ds.getConnection(); Statement st = c.createStatement();
             ResultSet rs = st.executeQuery(
                     "select room_code, last_activity_at, created_at from sessions")) {
            assertThat(rs.next()).isTrue();
            assertThat(rs.getString("room_code")).isEqualTo("ABCD1234");
            assertThat(rs.getTimestamp("last_activity_at")).isEqualTo(rs.getTimestamp("created_at"));
        }
    }

    // ====================================
    // Hilfsmethoden
    // ====================================

    private static JdbcDataSource newDatabase() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        return ds;
    }

    private static void migrate(JdbcDataSource ds) {
        Flyway.configure()
                .dataSource(ds)
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("0")
                .load()
                .migrate();
    }

    private static boolean columnExists(JdbcDataSource ds, String table, String column) throws SQLException {
        try (Connection c = ds.getConnection();
             ResultSet rs = c.getMetaData().getColumns(null, null, table, column)) {
            return rs.next();
        }
    }
}
