-- =========================================================
-- Ausgangsschema (Stand 1.1.0)
--
-- Bis 1.1.0 hat Hibernate das Schema per ddl-auto=update angelegt.
-- Bestehende Datenbanken werden deshalb bei Version 0 eingehängt
-- (spring.flyway.baseline-version=0) und dieses Skript läuft auch dort.
-- Alle Anweisungen sind idempotent: Eine leere Datenbank bekommt das
-- komplette Schema, eine bestehende nur, was ihr fehlt.
--
-- Enum-Spalten sind bewusst varchar ohne CHECK-Constraint, damit neue
-- Werte (z. B. Schätzmethoden) keine Migration brauchen.
-- =========================================================

CREATE TABLE IF NOT EXISTS sessions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_code          VARCHAR(8)   NOT NULL UNIQUE,
    current_ticket_id  BIGINT,
    estimation_method  VARCHAR(255) NOT NULL,
    status             VARCHAR(255) NOT NULL,
    created_at         TIMESTAMP(6) NOT NULL,
    show_topic         BOOLEAN      NOT NULL,
    moderator_can_vote BOOLEAN      NOT NULL,
    auto_reveal        BOOLEAN      NOT NULL,
    show_only_total    BOOLEAN      DEFAULT TRUE NOT NULL
);

CREATE TABLE IF NOT EXISTS participants (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    role       VARCHAR(255) NOT NULL,
    moderator  BOOLEAN      NOT NULL,
    joined_at  TIMESTAMP(6) NOT NULL,
    browser_id VARCHAR(36),
    token      VARCHAR(36),
    session_id BIGINT       NOT NULL,
    CONSTRAINT fk_participant_session FOREIGN KEY (session_id) REFERENCES sessions (id)
);

CREATE TABLE IF NOT EXISTS tickets (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(255) NOT NULL,
    status         VARCHAR(255) NOT NULL,
    final_estimate VARCHAR(20),
    order_index    INTEGER      NOT NULL,
    session_id     BIGINT       NOT NULL,
    CONSTRAINT fk_ticket_session FOREIGN KEY (session_id) REFERENCES sessions (id)
);

CREATE TABLE IF NOT EXISTS votes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_value     VARCHAR(10)  NOT NULL,
    voted_at       TIMESTAMP(6) NOT NULL,
    session_id     BIGINT       NOT NULL,
    participant_id BIGINT       NOT NULL,
    CONSTRAINT uq_vote_session_participant UNIQUE (session_id, participant_id),
    CONSTRAINT fk_vote_session     FOREIGN KEY (session_id)     REFERENCES sessions (id),
    CONSTRAINT fk_vote_participant FOREIGN KEY (participant_id) REFERENCES participants (id)
);

-- Datenbanken aus 1.0.x kennen das Teilnehmer-Token noch nicht
ALTER TABLE participants ADD COLUMN IF NOT EXISTS token VARCHAR(36);
CREATE UNIQUE INDEX IF NOT EXISTS uq_participant_token ON participants (token);
